### ISSUE TITLE
Define class <Match> in sneps.snip.matching

### ISSUE THREAD

**Issue by yousseftarekkh** [Java-SNePS/Java-SNePS-3.0#155]
**Description**
Class used to store matched nodes along with their dependencies, instead of previously used Object Array.

**Instance Variables**
- Substitutions filterSubs;
- Substitutions switchSubs;
- Node node;
- int matchType;

**Methods**
- _Getters & Setters for all instances_

**Comment by nadinehany** [comment]
I added it in the package and reviewed it.
