### ISSUE TITLE
Reimplement PropositionSet

### ISSUE THREAD

**Issue by moar55** [Java-SNePS/Java-SNePS-3.0#65]

**Comment by AmgadFarag** [comment]
Description pls?
what do you need

**Comment by moar55** [comment]
Sorry my bad, I meant to assign @AmrAhmedAli  not you :sweat_smile: .
We needed to re-implement the proposition set DS for the reasons stated in my last commit.

**Comment by nourhan-ehab** [comment]
I just assigned Amr and Unassigned Amgad.
